name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --extra test

    - name: Run tests
      run: uv run pytest tests/ -v

    - name: Run FastAPI in background
      run: |
        nohup uv run uvicorn src.main:app --host 127.0.0.1 --port 8080 > uvicorn.log 2>&1 &

    - name: Wait for FastAPI to start
      run: |
        for i in {1..20}; do
          if curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8080 | grep -q "^2"; then
            echo "FastAPI started."
            exit 0
          fi
          echo "Server not yet ready: attempt $i"
          sleep 1
        done

    - name: Export rendered HTML from FastAPI
      run: |
        mkdir -p dist
        curl http://127.0.0.1:8080 -o dist/index.html
        cp -r static dist/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Requires GENERAL_GITHUB_PAGES_TOKEN secret to be configured
        # See docs/DEPLOYMENT.md for setup instructions
        github_token: ${{ secrets.GENERAL_GITHUB_PAGES_TOKEN }}
        publish_dir: ./dist
