name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
        
    - name: Install dependencies
      run: uv sync
      
    - name: Build static site
      run: |
        # Create dist directory
        mkdir -p dist
        
        # Copy static files
        cp -r static dist/
        
        # Copy templates
        cp -r templates dist/
        
        # Create a static HTML file with embedded data
        python -c "
        import json
        from src.main import portfolio_data
        
        # Read the template
        with open('templates/index.html', 'r') as f:
            template_content = f.read()
        
        # Replace template variables with actual data
        html_content = template_content.replace('{{ portfolio.name }}', portfolio_data.name)
        html_content = html_content.replace('{{ portfolio.title }}', portfolio_data.title)
        html_content = html_content.replace('{{ portfolio.location }}', portfolio_data.location)
        html_content = html_content.replace('{{ portfolio.summary }}', portfolio_data.summary)
        html_content = html_content.replace('{{ portfolio.email }}', portfolio_data.email)
        html_content = html_content.replace('{{ portfolio.linkedin }}', portfolio_data.linkedin)
        html_content = html_content.replace('{{ portfolio.github }}', portfolio_data.github)
        
        # Replace static file paths
        html_content = html_content.replace('{{ url_for(\'static\', path=\'/css/style.css\') }}', './static/css/style.css')
        html_content = html_content.replace('{{ url_for(\'static\', path=\'/js/main.js\') }}', './static/js/main.js')
        
        # Write the static HTML file
        with open('dist/index.html', 'w') as f:
            f.write(html_content)
        
        print('Static site built successfully!')
        "
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist 